service: profile-service

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

plugins:
  - serverless-offline
  - serverless-dynamodb-local

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - nodemon.json
    - README.md

functions:
  index:
    handler: dist/lambda.handler
    events:
      - http:
          cors: true
          path: '/'
          method: any
      - http:
          cors: true
          path: '{proxy+}'
          method: any
